version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.3
    container_name: test
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test